### ISSUE TITLE
Eclipse jpa provider required "ClassNotFoundException: org.eclipse.persistence.jpa.PersistenceProvider "

### ISSUE THREAD

**Issue by learn-houseware** [divinespear/jpa-schema-maven-plugin#20]
Hi,
The project need both dependencies to work... May be using strings and invoke by reflection when the provider is required a simple solution?

**Caused by: java.lang.ClassNotFoundException: org.eclipse.persistence.jpa.PersistenceProvider**
`
static {
        PROVIDER_MAP.put(Vendor.eclipselink, org.eclipse.persistence.jpa.PersistenceProvider.class);
        PROVIDER_MAP.put(Vendor.hibernate, org.hibernate.jpa.HibernatePersistenceProvider.class);
        // PROVIDER_MAP.put(Vendor.datanucleus, org.datanucleus.api.jpa.PersistenceProviderImpl.class);
    }`

**Comment by divinespear** [comment]
It's too late, but I think it fixed with 0.2.1. Please test it.
