### ISSUE TITLE
JavaEE

### ISSUE THREAD

**Issue by madoar** [divinespear/jpa-schema-maven-plugin#21]
Hi,
I want to use the jpa-schema-maven-plugin to create a sql file containing the database schema of an javaee application with jboss/wildfly dependencies.
In my case this means that all dependencies have a provided scope and hibernate isn't added to the pom file because it gets automatically provided by the wildfly application server.
When I try to use the jpa-schema-maven-plugin plugin with this setup I get a lot of NoClassDefFoundError exceptions, because implementations for the used libraries in my database project are not available at compile-time, they are only available at runtime in the application server.
I've tried to add the hibernate to the dependencies environment inside the plugin definition environment, but it seems like it gets ignored by the plugin.

Is there an easy way to use this plugin in with javaee applications that don't have the implementations of some libraries at compile time?
Otherwise is it possible to extend this plugin that it's possible to provide the needed implementation dependencies in the dependencies environment inside the plugin definition environment?

Many Greetings
madoar

**Comment by divinespear** [comment]
It's too late, but I think it fixed with 0.2.1. Please test it.
