### ISSUE TITLE
jta-data-source again

### ISSUE THREAD

**Issue by vagy13** [divinespear/jpa-schema-maven-plugin#22]
Hi,
actually I have exactly the same issue as #16 .
I think you fixed the issue in the codebase of your gradle plugin but the fix didn't make it here (?).
Nice work!

**Comment by divinespear** [comment]
Did you mean issue like divinespear/jpa-schema-gradle-plugin#26?

**Comment by vagy13** [comment]
Yes, I assume issue #26 in your Gradle plugin has the same root cause as issue #16 in your Maven plugin
since they are both caused by a javax.naming.NoInitialContextException with the same exception reason.
I may be wrong though. In any case issue #16 is still relevant for your Maven plugin.

**Comment by divinespear** [comment]
Ah... travis said It looks good.
I'll release this 0.2.1 soon.

**Comment by vagy13** [comment]
Many thanks! I'll test it asap.
